name: Cron Workflows
on:
  schedule:
  - cron: '0 0 * * *'
env:
  GITHUB_TOKEN: ${{ secrets.ZOWE_ROBOT_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch: ['master', 'zowe-v1-lts', 'zowe-v2-lts']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Scripts
        run: gh workflow run -r ${{ matrix.branch }} test.yml

      - name: WebHelp CI
        run: gh workflow run -r ${{ matrix.branch }} -f release=false main.yml
